# Data Preparation Steps

## RIGA Income Aggregates

This study combines micro data for 4 countries across multiple survey years. To expedite all data reconciliation and preparation steps we choose to rely as much as possible on FAO/RIGA cross-country harmonized database of income aggregates. These aggregates are used to estimate both farm and crop sales and farm vs. non-farm income. Generally in the RIGA approach the method is (see @riga2007doco):

- All aggregates are estimated at the household level.  
- All income and expenditures are **annualized**.  
- All income components are **net of costs**.  
- Purchases and sales of **durable goods**, investments and windfall gains are excluded from household income and expenditure calculations since these are not transactions undertaken regularly by households and can result in the significant over- or under-stating of permanent income.  
- All aggregates are reported in **local currency units (LCU)**.  
- For each survey, only the **rural** sample is used (this is not consustent across all surveys)  
- An outlier check is imposed after the construction of all income aggregates to deal with extreme income shares that arise following the aggregation of all income components. After estimating the shares of the seven principal income categories (agricultural wages, non-agricultural wages, crop, livestock, self employment, transfer and other) **observations whose share is greater than or less than 3 (indicating a percentage share of +/- 300%) are dropped from the aggregate**.  

However because RIGA income aggregates are *net of costs*, we use intermediary components instead. Details are also shown in the table below.

- $cropsales$ derived from $totcropsold$
- $cropvalue$ derived from $totcropprod$
- $cropsales\_sh$ (but can also be derived from $shcropsold$ and $shagprodsold$)
  $$ cropsales\_sh = \frac{cropsales}{cropvalue} $$ 
- $agsales$ derived from $totagsold$
- $aggross = totagprod + farmrntimp + agr\_wge (+ selfimp1)$
- $naggross = transfersgrossimp + otherincimp + nonfarmrntimp + nonagr\_wge + selfemp$
- $totgross = aggross + naggross$  
- $aggross\_sh$  
  $$ aggross\_sh = \frac{aggross}{totgross} $$  

RIGA does not provide annual cultivated area, instead we have measures of land owned, land rented out, and land under sharecropping.

## Harmonized Codebook

```{r prep, results="asis"}

tmp <- fread("../data/codebook.csv")
tmp[, `:=`(
  section = tools::toTitleCase(section),
  varLabel = str_replace(sprintf("%s (%s)", varLabel, unit), fixed(" ()"), "")
  )]

table_options(HTMLcaption="(#tab:prep) Cross-country harmonized household-level variables")
html(tabular((Section=(Factor(section)))*(Variable=Factor(varCode))*DropEmpty()~(Heading(Label)*varLabel+Heading(Source)*source*Heading())*identity, 
  data=tmp), rmarkdown=TRUE, align="l", align.header="l")

```


